amcl:
  ros__parameters:
    robot_model_type: "differential"

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_frame: odom

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      # KOBUKI FOOTPRINT CONFIGURATION
      robot_radius: 0.175  # 17.5cm radius for the Kobuki base
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55 # Buffer zone
        cost_scaling_factor: 3.0

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.175